[package]
name = "rusty_resizer"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "rusty_resizer"


[dependencies]
actix-http = "3.0.1"
actix-web = "4.0.1"
awc = { version = "=3.0.0-beta.21", features = ["openssl"] }
env_logger = "0.9.0"
httpdate = "1.0.1"
log = "0.4.14"
magick_rust = { git = "https://github.com/nlfiedler/magick-rust", branch = "master", features = ["disable-hdri"] }
openssl = "0.10.36"
serde = { version = "1.0.136", features = ["derive"] }
url = "2.2.2"

[dev-dependencies]
actix-rt = "2.2.0"
reqwest = "0.11.4"
tokio = "1.12.0"
image = "0.24.1"