[package]
name = "rusty_resizer"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "rusty_resizer"


[dependencies]
actix-web = "=4.0.0-beta.9"
actix-http = "=3.0.0-beta.10"
awc = { version = "=3.0.0-beta.8", features = ["openssl"] }
env_logger = "0.9.0"
log = "0.4.14"
magick_rust = "0.15.0"
openssl = "0.10.36"
serde = "1.0.130"

[dev-dependencies]
actix-rt = "2.2.0"
reqwest = "0.11.4"
tokio = "1.12.0"
image = "0.23.14"