[package]
name = "rusty_resizer"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = { version = "3", features = ["openssl"] }
env_logger = "0.9.0"
log = "0.4.14"
magick_rust = "0.15.0"
openssl = "0.10.36"
serde = "1.0.130"

[dev-dependencies]
actix-rt = "2.2.0"